# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Publish with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    -   name: Reposilite credentials
        env:
            REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
            REPOSILITE_TOKEN: ${{ secrets.REPOSILITE_TOKEN }}
        shell: bash
        run: |
            touch gradle.properties
            echo "reposilite.username=${REPOSILITE_USERNAME}" &>> gradle.properties
            echo "reposilite.token=${REPOSILITE_TOKEN}" &>> gradle.properties
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean assemble
    - name: Publish
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
          arguments: publish
